### PR TITLE
Add venv & interestingness tests

### PR DESCRIPTION
**Pull request by jschwartzentruber**
This adds tests to make sure setup.py doesn't break, and that interesting tests work as expected.

Calling LithiumTests.test_arithmetic in the venv also ensures that we can call interestingness scripts by path (not part of the lithium module).

This is a cleanup of some of the travis/appveyor tests @nth10sd came up with in #28 & #33 by porting them to unittests.

### CODE REVIEW

**Comment by jschwartzentruber** [comment]
This passes except for the fileIngredients unicode problems discussed in #33.

**Comment by nth10sd** [comment]
Looks good so far, sans me nitpicking the `if sys.platform.startswith("win")` portion as we had discussed. I forgot our conclusion about using the `platform` module though.

**Comment by jschwartzentruber** [comment]
Good call. We agreed to use platform.system() consistently. I'll push the update after #39 lands so the tests go green :-)

**Comment by jschwartzentruber** [comment]
The virtualenv test is failing on Travis due to system module differences. I'll have to investigate.

**Comment by jschwartzentruber** [comment]
I will split this into separate PRs, since the interestingness tests are much simpler.

**Pull request closed without merging**
